version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 12
    commands:
      - npm i
  pre_build:
    commands:
      - echo "prebuilding?"
  build:
    commands:
      - npm run build
  post_build:
    commands:
      - echo "DONE"
      - echo $CODEBUILD_SOURCE_VERSION
      - aws s3 sync build/ s3://$ASSETS_BUCKET && aws cloudfront create-invalidation --distribution-id="$ASSETS_CDN_ID" --path="/*"
 
